### ISSUE TITLE
make a new 4.2.0 release?

### ISSUE THREAD

**Issue by sezero** [libxmp/xmp-cli#31]
What is needed to make a new 4.2.0 release?

**Comment by AliceLR** [comment]
No clue currently, but I'll go ahead and pin this issue.

**Comment by AliceLR** [comment]
Going down the list of open issues, I think #14, #25, and #26 should definitely be resolved. I'm not familiar enough with libnotify to handle #8, but it doesn't seem unreasonable. #32 (which I just opened) has been annoying for a while but isn't particularly serious.

#4 looks like a libxmp bug and I suspect some context is missing, because I've never encountered it, or it was fixed at some point.

**Comment by mistydemeo** [comment]
It looks like there's a commit that labels a "4.2.0" release, but it wasn't tagged or released as a tarball: fa8286eeb1deb4a5679169bdf798039552fe6067 Are there any plans for that?

**Comment by sezero** [comment]
Still waiting for things to clear up.

**Comment by sezero** [comment]
What do we definitely do before doing a 4.2.0 release?

**Comment by AliceLR** [comment]
None of the things I listed are essential for a release, I think this could be done any time.

**Comment by sezero** [comment]
Tagged and created a 4.2.0 release: https://github.com/libxmp/xmp-cli/releases/tag/xmp-4.2.0
